version = 1

[[analyzers]]
name = "php"

test_patterns = [
  "tests/**"
]

exclude_patterns = [
  "node_modules/**",
  "vendor/**",
  "public/**",
]


[[analyzers]]
name = "php"
enabled = true

name = "javascript"
enabled = true

[analyzers.meta]
  plugins = ["vue"]
