version = 1

exclude_patterns = [
  "node_modules/**",
  "vendor/**",
  "public/**",
]

[[analyzers]]
name = "php"
enabled = true

test_patterns = [
  "tests/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["vue"]
