version = 1

test_patterns = [
  "tests/**"
]

exclude_patterns = [
  "node_modules/**",
  "public/**",
  "vendor/**",
]

[[analyzers]]
name = "php"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["vue"]
