<template>
    <!-- eslint-disable -->
    <div class="block__body">
        <a17-vselect label="Modal Type" :name="fieldName('modal_type')" :options='[{&quot;value&quot;:&quot;image&quot;,&quot;label&quot;:&quot;Image&quot;},{&quot;value&quot;:&quot;video&quot;,&quot;label&quot;:&quot;Video&quot;},{&quot;value&quot;:&quot;image_sequence&quot;,&quot;label&quot;:&quot;Image Sequence&quot;}]' placeholder="Choose Modal Type" :selected="{&quot;value&quot;:&quot;image&quot;,&quot;label&quot;:&quot;Image&quot;}" :has-default-store="true" size="large" in-store="inputValue" > </a17-vselect><a17-connectorfield :is-value-equal="true" :keep-alive="true" :field-name="fieldName('modal_type')" :required-field-values="'image'" > <a17-singlecheckbox :name="fieldName('zoomable')" label="Zoomable" :initial-value="false" :has-default-store="true" in-store="currentValue"
></a17-singlecheckbox> <a17-singleselect label="Experience Image" :name="fieldName('has_experience_image')" :options="[{&quot;value&quot;:true,&quot;label&quot;:&quot;On&quot;},{&quot;value&quot;:false,&quot;label&quot;:&quot;Off&quot;}]" :grid="false" :inline="true" :has-default-store="true" in-store="value"
> </a17-singleselect> <a17-connectorfield :is-value-equal="true" :field-name="fieldName('has_experience_image')" :required-field-values="true" > <a17-inputframe label="Image" name="medias.experience_image" > <a17-mediafield :name="fieldName('experience_image')" crop-context="experience_image" ></a17-mediafield> </a17-inputframe><a17-singleselect label="Inline Credits" :name="fieldName('inline_credits')" :options="[{&quot;value&quot;:&quot;on&quot;,&quot;label&quot;:&quot;On&quot;},{&quot;value&quot;:&quot;off&quot;,&quot;label&quot;:&quot;Off&quot;}]" selected="off" :grid="false" :inline="true" :has-default-store="true" in-store="value"
> </a17-singleselect><a17-connectorfield :is-value-equal="true" :field-name="fieldName('inline_credits')" :required-field-values="'on'" > <a17-singleselect label="Credits Input" :name="fieldName('credits_input')" :options="[{&quot;value&quot;:&quot;datahub&quot;,&quot;label&quot;:&quot;Datahub&quot;},{&quot;value&quot;:&quot;manual&quot;,&quot;label&quot;:&quot;Manual&quot;}]" selected="datahub" :grid="false" :inline="true" :has-default-store="true" in-store="value"
> </a17-singleselect> <a17-connectorfield :is-value-equal="true" :field-name="fieldName('credits_input')" :required-field-values="'datahub'" > <a17-textfield label="Object ID" :name="fieldName('object_id')" type="text" in-store="value" ></a17-textfield></a17-connectorfield> <a17-connectorfield :is-value-equal="true" :field-name="fieldName('credits_input')" :required-field-values="'manual'" > <a17-textfield label="Artist" :name="fieldName('artist')" type="text" in-store="value" ></a17-textfield> <a17-textfield label="Title" :name="fieldName('credit_title')" type="text" in-store="value" ></a17-textfield> <a17-textfield label="Date" :name="fieldName('credit_date')" type="text" in-store="value" ></a17-textfield> <a17-textfield label="Medium" :name="fieldName('medium')" type="text" in-store="value" ></a17-textfield> <a17-textfield label="Dimensions" :name="fieldName('dimensions')" type="text" in-store="value" ></a17-textfield> <a17-textfield label="Credit Line" :name="fieldName('credit_line')" type="text" in-store="value" ></a17-textfield> <a17-textfield label="Main Reference Number" :name="fieldName('main_reference_number')" type="text" in-store="value" ></a17-textfield> <a17-textfield label="Copyright Notice" :name="fieldName('copyright_notice')" type="text" in-store="value" ></a17-textfield></a17-connectorfield></a17-connectorfield></a17-connectorfield></a17-connectorfield><a17-connectorfield :is-value-equal="true" :field-name="fieldName('modal_type')" :required-field-values="'video'" > <a17-textfield label="Youtube URL" :name="fieldName('video_url')" type="text" in-store="value" ></a17-textfield> <a17-multiselect label="Video Player Setting" :name="fieldName('video_play_settings')" :options="[{&quot;value&quot;:&quot;autoplay&quot;,&quot;label&quot;:&quot;Autoplay&quot;},{&quot;value&quot;:&quot;controls_dark&quot;,&quot;label&quot;:&quot;Controls Dark&quot;},{&quot;value&quot;:&quot;controls_light&quot;,&quot;label&quot;:&quot;Controls Light&quot;}]" :grid="true" :inline="false" :min="1" :max="3" in-store="currentValue" > </a17-multiselect> <a17-multiselect label="playback" :name="fieldName('video_playback')" :options="[{&quot;value&quot;:&quot;inset&quot;,&quot;label&quot;:&quot;Inset&quot;},{&quot;value&quot;:&quot;caption&quot;,&quot;label&quot;:&quot;Caption&quot;},{&quot;value&quot;:&quot;loop&quot;,&quot;label&quot;:&quot;Loop&quot;}]" :grid="true" :inline="false" in-store="currentValue" > </a17-multiselect></a17-connectorfield><a17-connectorfield :is-value-equal="true" :field-name="fieldName('modal_type')" :required-field-values="'image_sequence'" > <a17-locale type="a17-filefield" :attributes="{ label: 'Image Sequence Zip', itemLabel: 'image sequence zip', name: fieldName('image_sequence_file'), note: 'Upload a .zip file', max: 1 }"
></a17-locale> <a17-multiselect label="playback" :name="fieldName('image_sequence_playback')" :options="[{&quot;value&quot;:&quot;reverse&quot;,&quot;label&quot;:&quot;Reverse&quot;},{&quot;value&quot;:&quot;infinite&quot;,&quot;label&quot;:&quot;Infinite&quot;}]" :grid="true" :inline="false" in-store="currentValue" > </a17-multiselect> <a17-textfield label="Caption" :name="fieldName('image_sequence_caption')" type="text" in-store="value" ></a17-textfield></a17-connectorfield>
    </div>
</template>

<script>
  import BlockMixin from '@/mixins/block'

  export default {
    mixins: [BlockMixin]
  }
</script>
