@component('components.molecules._m-listing----media')
    @slot('tag', $tag ?? null)
    @slot('titleFont', $titleFont ?? null)
    @slot('variation', $variation ?? null)
    @slot('imgVariation', $imgVariation ?? null)
    @slot('imageSettings', $imageSettings ?? null)
    @slot('embed', $embed ?? null)
    @slot('fullscreen', $fullscreen ?? null)
    @slot('item', $item)
    @slot('gtmAttributes', $gtmAttributes ?? null)
@endcomponent
